//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedAppDBEntities : DbContext
    {
        public MedAppDBEntities()
            : base("name=MedAppDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Day> Day { get; set; }
        public virtual DbSet<Diagnosis> Diagnosis { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Medicament> Medicament { get; set; }
        public virtual DbSet<MedRecord> MedRecord { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Shift> Shift { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<Timetable> Timetable { get; set; }
        public virtual DbSet<Visiting> Visiting { get; set; }
        public virtual DbSet<Xrays> Xrays { get; set; }
    }
}
