//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedApp.Models
{
    using System;
    using System.Collections.Generic;
    using Prism.Mvvm;
    using System.ComponentModel;
    public partial class Shift : BindableBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shift()
        {
            this.Timetable = new HashSet<Timetable>();
        }
    
        private int  _Id;
        public int Id 
        { 
           get
           {
              return _Id;
           } 
           set
           {
              if(_Id != value)
              {
                _Id = value;
                RaisePropertyChanged("Id");
              }
           }
        }
     
        private string  _Name;
        public string Name 
        { 
           get
           {
              return _Name;
           } 
           set
           {
              if(_Name != value)
              {
                _Name = value;
                RaisePropertyChanged("Name");
              }
           }
        }
     
        private System.TimeSpan  _Begin_work;
        public System.TimeSpan Begin_work 
        { 
           get
           {
              return _Begin_work;
           } 
           set
           {
              if(_Begin_work != value)
              {
                _Begin_work = value;
                RaisePropertyChanged("Begin_work");
              }
           }
        }
     
        private System.TimeSpan  _End_work;
        public System.TimeSpan End_work 
        { 
           get
           {
              return _End_work;
           } 
           set
           {
              if(_End_work != value)
              {
                _End_work = value;
                RaisePropertyChanged("End_work");
              }
           }
        }
     
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<Timetable> _Timetable;
        public virtual ICollection<Timetable> Timetable 
        { 
          get
          {
              return _Timetable;
          } 
          set
          {
             if(_Timetable != value)
             {
                _Timetable = value;
                RaisePropertyChanged("Timetable");
             }
          }
        }
     
    }
}
