//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedApp.Models
{
    using System;
    using System.Collections.Generic;
    using Prism.Mvvm;
    using System.ComponentModel;
    public partial class Xrays : BindableBase
    {
        private int  _Id;
        public int Id 
        { 
           get
           {
              return _Id;
           } 
           set
           {
              if(_Id != value)
              {
                _Id = value;
                RaisePropertyChanged("Id");
              }
           }
        }
     
        private byte[]  _Photo;
        public byte[] Photo 
        { 
           get
           {
              return _Photo;
           } 
           set
           {
              if(_Photo != value)
              {
                _Photo = value;
                RaisePropertyChanged("Photo");
              }
           }
        }
     
        private System.DateTime  _Date;
        public System.DateTime Date 
        { 
           get
           {
              return _Date;
           } 
           set
           {
              if(_Date != value)
              {
                _Date = value;
                RaisePropertyChanged("Date");
              }
           }
        }
     
        private string  _Description;
        public string Description 
        { 
           get
           {
              return _Description;
           } 
           set
           {
              if(_Description != value)
              {
                _Description = value;
                RaisePropertyChanged("Description");
              }
           }
        }
     
        private int  _IdMedRecord;
        public int IdMedRecord 
        { 
           get
           {
              return _IdMedRecord;
           } 
           set
           {
              if(_IdMedRecord != value)
              {
                _IdMedRecord = value;
                RaisePropertyChanged("IdMedRecord");
              }
           }
        }
     
    
        private MedRecord _MedRecord;
        public virtual MedRecord MedRecord 
        { 
          get
          {
              return _MedRecord;
          } 
          set
          {
             if(_MedRecord != value)
             {
                _MedRecord = value;
                RaisePropertyChanged("MedRecord");
             }
          }
        }
     
    }
}
